# Generated by Django 5.0.3 on 2024-05-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0002_rename_doc_document'),
        ('webapp', '0004_alter_group_modified_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('group_id', 'doc_name')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
