# Generated by Django 5.0.3 on 2024-04-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_password', models.CharField(default=None, max_length=81, null=True)),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_user_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readable', models.BooleanField(default=True)),
                ('writable', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.document')),
            ],
            options={
                'unique_together': {('doc_id', 'user_id')},
            },
        ),
    ]
