# Generated by Django 5.0.3 on 2024-05-12 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_group_grp_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grp_user_permission',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.group'),
        ),
    ]
