# Generated by Django 5.0.3 on 2024-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_grp_user_permission_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
