# Generated by Django 5.0.3 on 2024-05-23 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('webapp', '0004_alter_group_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grp_join_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'unique_together': {('group_id', 'user_id')},
            },
        ),
    ]
