# Generated by Django 5.0.3 on 2024-06-02 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('webapp', '0007_delete_curr_joined_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curr_joined_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'unique_together': {('group_id', 'user_id')},
            },
        ),
    ]
