# Generated by Django 5.0.3 on 2024-06-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_curr_joined_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curr_joined_member',
        ),
    ]
